### ISSUE TITLE
Add the AUR package to the README

### ISSUE THREAD

**Issue by ChausseBenjamin** [zeljkobekcic/fff#1]
Hey,
I just added your package to the arch user repository:
[https://aur.archlinux.org/packages/fff-ueberzug-git/](https://aur.archlinux.org/packages/fff-ueberzug-git/)

Perhaps you could add it to the readme under the installation section.

**Comment by zeljkobekcic** [comment]
Hey Benjamin, sure! Thank you for the aur package, now I can install it via the AUR!
